import { ReactElement } from 'react'

import { RecipeResponse } from 'core/api/autogenerated/data-contracts'

interface RecipeCardProps {
  info: RecipeResponse
}

function RecipeCard({ info }: RecipeCardProps): ReactElement {
  return (
    <div className="recipe-card">
      <div className="recipe-card__title">{info.name}</div>
      <div className="recipe-card__description">{info.description}</div>
    </div>
  )
}

export default RecipeCard
