import { ApiController } from 'core/api/autogenerated/Api'
import { useCallback } from 'react'
import useQuery from 'core/api/react-query/use-query'

function useRecipes() {
  const request = useCallback(() => {
    const controller = new ApiController()

    return controller.v1RecipesList()
  }, [])

  return useQuery('recipes', request)
}

export default useRecipes
